### ISSUE TITLE
Country display is borked in account/show

### ISSUE THREAD

**Issue by srogers** [srogers/conferences#437]
Breaks for non-US country, because user.location() didn't get ported over to the new options format.

**Comment by srogers** [comment]
```
TypeError: no implicit conversion of Symbol into Integer
  app/helpers/application_helper.rb:319:in `[]'
    thing.location(thing.country == 'US' ? { country_format: false } : { country_format: options[:country_format] || :short })
  app/helpers/application_helper.rb:319:in `location_with_non_us_country'
    thing.location(thing.country == 'US' ? { country_format: false } : { country_format: options[:country_format] || :short })
  app/views/accounts/show.html.haml:18:in `_app_views_accounts_show_html_haml__3669496807896291650_47358358161980'
    = location_with_non_us_country @user, :short
...
(100 additional frame(s) were not displayed)

ActionView::Template::Error: no implicit conversion of Symbol into Integer
```
