### ISSUE TITLE
Search is weird

### ISSUE THREAD

**Issue by srogers** [srogers/conferences#441]
For example - try to do a search on psycho-epistemology and Binswanger - the only way is to search Binswanger and then find a psycho-epistemology tag and click it.

typing in psycho-epistemology get that in both boxes with OR - but then there's no way to run that search. The magnifying glass clears things, which seems wrong.

**Comment by srogers** [comment]
Error in production:  

NoMethodError: undefined method `group' for nil:NilClass
```  
app/controllers/concerns/presentations_chart.rb:111:in `topic_count_data'
    data = @presentations.group('tags.name').count(:all)
  app/controllers/presentations_controller.rb:72:in `chart'
    @presentations = topic_count_data.sort_by{|topic,count| count }.reverse
```
(67 additional frame(s) were not displayed
